// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQsY3dhfB4dJw1k6BuMS4vEDdnLra5EXI',
    appId: '1:259660848900:web:c4765f68220496f19c3a51',
    messagingSenderId: '259660848900',
    projectId: 'first-project-e4abf',
    authDomain: 'first-project-e4abf.firebaseapp.com',
    storageBucket: 'first-project-e4abf.appspot.com',
    measurementId: 'G-GWLZ99ZSKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsZklD5QhT2_Vclu9Ns-cEWj0w39503EU',
    appId: '1:259660848900:android:6192ca2b4ff86fbd9c3a51',
    messagingSenderId: '259660848900',
    projectId: 'first-project-e4abf',
    storageBucket: 'first-project-e4abf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_7fMPMa-t2ztMWsrVEq-R92W3dd5vOA',
    appId: '1:259660848900:ios:fe1a6b9f808768359c3a51',
    messagingSenderId: '259660848900',
    projectId: 'first-project-e4abf',
    storageBucket: 'first-project-e4abf.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );
}
